import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import crypto from 'node:crypto';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import pg from 'pg';
const {Pool}=pg; const app=express();
app.use(helmet({contentSecurityPolicy:false}));
app.use(cors({origin:process.env.CORS_ORIGIN?.split(',').map(s=>s.trim())||true,credentials:true})); app.use(express.json({limit:'1mb'}));
const pool=process.env.DATABASE_URL?new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.PGSSL==='disable'?false:{rejectUnauthorized:false}}):null;
const id=()=>crypto.randomUUID(), now=()=>new Date().toISOString();
async function db(sql,p=[]){if(!pool)throw Error('DATABASE_URL is not configured');return pool.query(sql,p)}
async function init(){if(!pool)return;await db(`CREATE TABLE IF NOT EXISTS tenants(id uuid PRIMARY KEY,name text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());`);await db(`CREATE TABLE IF NOT EXISTS users(id uuid PRIMARY KEY,tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,user_id text NOT NULL,name text NOT NULL,email text NOT NULL,password_hash text NOT NULL,role text NOT NULL DEFAULT 'owner',profile jsonb NOT NULL DEFAULT '{}'::jsonb,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,user_id),UNIQUE(tenant_id,email));`);await db(`CREATE TABLE IF NOT EXISTS records(tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,record_type text NOT NULL,record_id text NOT NULL,user_id text,data jsonb NOT NULL DEFAULT '{}'::jsonb,updated_at timestamptz NOT NULL,deleted_at timestamptz,PRIMARY KEY(tenant_id,record_type,record_id));`);await db(`CREATE INDEX IF NOT EXISTS records_tenant_type_idx ON records(tenant_id,record_type);`);await db(`CREATE INDEX IF NOT EXISTS records_updated_idx ON records(tenant_id,updated_at);`)}
function auth(req,res,next){const h=req.headers.authorization||'',t=h.startsWith('Bearer ')?h.slice(7):null;if(!t)return res.status(401).json({error:'missing_token'});try{req.auth=jwt.verify(t,process.env.JWT_SECRET);next()}catch{return res.status(401).json({error:'invalid_token'})}}
const tokenFor=u=>jwt.sign({sub:u.id,tenantId:u.tenant_id,userId:u.user_id,role:u.role},process.env.JWT_SECRET,{expiresIn:process.env.JWT_EXPIRES||'12h'});
app.get('/api/health',(q,s)=>s.json({ok:true,service:'geniuspos-api',time:now()}));
app.post('/api/auth/register',async(req,res)=>{try{const{name,email,password,businessName='Genius Business'}=req.body||{};if(!name||!email||!password||String(password).length<8)return res.status(400).json({error:'name_email_password_required'});const tenantId=id(),userUuid=id(),userId=`GEN-${Date.now().toString(36).toUpperCase()}-${crypto.randomBytes(3).toString('hex').toUpperCase()}`,hash=await bcrypt.hash(String(password),12);await db('BEGIN');await db('INSERT INTO tenants(id,name) VALUES($1,$2)',[tenantId,businessName]);await db('INSERT INTO users(id,tenant_id,user_id,name,email,password_hash,profile) VALUES($1,$2,$3,$4,$5,$6,$7)',[userUuid,tenantId,userId,name,String(email).toLowerCase(),hash,JSON.stringify({businessName,balance:0,twoStep:false,preferences:{theme:'system'}})]);await db('COMMIT');const u={id:userUuid,tenant_id:tenantId,user_id:userId,name,email:String(email).toLowerCase(),role:'owner',profile:{businessName,balance:0,twoStep:false,preferences:{theme:'system'}}};res.status(201).json({token:tokenFor(u),user:u})}catch(e){try{await db('ROLLBACK')}catch{};res.status(e.code==='23505'?409:500).json({error:e.code==='23505'?'account_exists':'server_error'})}});
app.post('/api/auth/login',async(req,res)=>{try{const{email,password}=req.body||{},r=await db('SELECT * FROM users WHERE email=$1 ORDER BY created_at LIMIT 1',[String(email||'').toLowerCase()]);if(!r.rowCount||!(await bcrypt.compare(String(password||''),r.rows[0].password_hash)))return res.status(401).json({error:'invalid_credentials'});const u=r.rows[0];res.json({token:tokenFor(u),user:{id:u.id,tenant_id:u.tenant_id,user_id:u.user_id,name:u.name,email:u.email,role:u.role,profile:u.profile}})}catch{res.status(500).json({error:'server_error'})}});
app.get('/api/me',auth,async(req,res)=>{const r=await db('SELECT id,tenant_id,user_id,name,email,role,profile FROM users WHERE id=$1',[req.auth.sub]);res.status(r.rowCount?200:404).json(r.rowCount?r.rows[0]:{error:'not_found'})});
app.post('/api/sync/push',auth,async(req,res)=>{try{const records=Array.isArray(req.body?.records)?req.body.records:[];if(records.length>1000)return res.status(413).json({error:'too_many_records'});await db('BEGIN');for(const r of records){if(!r?.type||!r?.id)continue;const t=new Date(r.updatedAt||Date.now()).toISOString();await db(`INSERT INTO records(tenant_id,record_type,record_id,user_id,data,updated_at,deleted_at) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(tenant_id,record_type,record_id) DO UPDATE SET user_id=EXCLUDED.user_id,data=EXCLUDED.data,updated_at=EXCLUDED.updated_at,deleted_at=EXCLUDED.deleted_at WHERE records.updated_at<=EXCLUDED.updated_at`,[req.auth.tenantId,String(r.type),String(r.id),r.userId||req.auth.userId,JSON.stringify(r.data||{}),t,r.deletedAt?new Date(r.deletedAt):null])}await db('COMMIT');res.json({ok:true,count:records.length,serverTime:now()})}catch{try{await db('ROLLBACK')}catch{};res.status(500).json({error:'sync_failed'})}});
app.get('/api/sync/pull',auth,async(req,res)=>{try{const since=req.query.since?new Date(req.query.since):new Date(0),r=await db(`SELECT record_type AS type,record_id AS id,user_id,data,updated_at,deleted_at FROM records WHERE tenant_id=$1 AND updated_at>$2 ORDER BY updated_at ASC LIMIT 5000`,[req.auth.tenantId,since]);res.json({records:r.rows.map(x=>({...x,updatedAt:x.updated_at,deletedAt:x.deleted_at}))})}catch{res.status(500).json({error:'sync_failed'})}});
app.get('/api/records/:type',auth,async(req,res)=>{try{const r=await db('SELECT record_id AS id,user_id,data,updated_at,deleted_at FROM records WHERE tenant_id=$1 AND record_type=$2 AND deleted_at IS NULL ORDER BY updated_at DESC LIMIT 5000',[req.auth.tenantId,req.params.type]);res.json(r.rows)}catch{res.status(500).json({error:'server_error'})}});
app.post('/api/records/:type',auth,async(req,res)=>{try{const rid=req.body?.id||id();await db(`INSERT INTO records(tenant_id,record_type,record_id,user_id,data,updated_at) VALUES($1,$2,$3,$4,$5,now()) ON CONFLICT(tenant_id,record_type,record_id) DO UPDATE SET data=EXCLUDED.data,user_id=EXCLUDED.user_id,updated_at=now(),deleted_at=NULL`,[req.auth.tenantId,req.params.type,rid,req.auth.userId,JSON.stringify(req.body?.data||req.body||{})]);res.status(201).json({id:rid})}catch{res.status(500).json({error:'server_error'})}});
app.delete('/api/records/:type/:id',auth,async(req,res)=>{try{await db('UPDATE records SET deleted_at=now(),updated_at=now() WHERE tenant_id=$1 AND record_type=$2 AND record_id=$3',[req.auth.tenantId,req.params.type,req.params.id]);res.json({ok:true})}catch{res.status(500).json({error:'server_error'})}});
app.get('/api/export',auth,async(req,res)=>{try{const r=await db('SELECT record_type AS type,record_id AS id,user_id,data,updated_at,deleted_at FROM records WHERE tenant_id=$1 ORDER BY updated_at',[req.auth.tenantId]);res.json({tenantId:req.auth.tenantId,exportedAt:now(),records:r.rows})}catch{res.status(500).json({error:'server_error'})}});
app.use(express.static(new URL('../',import.meta.url).pathname));
const port=Number(process.env.PORT||3000);init().then(()=>app.listen(port,()=>console.log(`Genius POS web/API server listening on :${port}`))).catch(e=>{console.error(e);process.exit(1)});
